SST: SST::Core::ThreadSafe::Barrier Class Reference
SST::Core::ThreadSafe::Barrier Class Reference
Public Member Functions
Barrier (size_t count)
void resize (size_t newCount)
ONLY call this while nobody is in wait()
double wait ()
Wait for all threads to reach this point.
void disable ()
Member Function Documentation
double SST::Core::ThreadSafe::Barrier::wait () inline
Wait for all threads to reach this point.
Returns
0.0, or elapsed time spent waiting, if configured with –enable-profile
Referenced by SST::Simulation::complete(), SST::ThreadSync::execute(), SST::Simulation::initialize(), and SST::Simulation::setup().
The documentation for this class was generated from the following file:
src/sst/core/threadsafe.h