SST: SST::StopAction Class Reference
SST::StopAction Class Reference
Action which causes the Simulation to end.
#include <stopAction.h>
Public Member Functions
StopAction (std::string msg)
Create a new StopAction which includes a message to be printed when it fires.
void execute () override
Function which will be called when the time for this Activity comes to pass.
void print (const std::string &header, Output &out) const override
Generic print-print function for this Activity.
Public Member Functions inherited from SST::Activity
void setDeliveryTime (SimTime_t time)
Set the time for which this Activity should be delivered.
SimTime_t getDeliveryTime () const
Return the time at which this Activity will be delivered.
int getPriority () const
Return the Priority of this Activity.
void setQueueOrder (uint64_t order)
Set a new Queue order.
Public Member Functions inherited from SST::Core::Serialization::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual std::string serialization_name () const =0
Additional Inherited Members
Protected Types inherited from SST::Core::Serialization::serializable
enum cxn_flag_t { ConstructorFlag }
Protected Member Functions inherited from SST::Action
void endSimulation ()
Called to signal to the Simulation object to end the simulation.
void endSimulation (SimTime_t end)
Protected Member Functions inherited from SST::Activity
void setPriority (int priority)
Set the priority of the Activity.
void serialize_order (SST::Core::Serialization::serializer &ser) override
Static Protected Member Functions inherited from SST::Core::Serialization::serializable
static void serializable_abort (uint32_t line, const char *file, const char *func, const char *obj)
Protected Attributes inherited from SST::Activity
int32_t enforce_link_order
Detailed Description
Action which causes the Simulation to end.
Member Function Documentation
void SST::StopAction::execute () inline override virtual
Function which will be called when the time for this Activity comes to pass.
Implements SST::Activity.
References SST::Action::endSimulation().
void SST::StopAction::print (const std::string & header, Output & out) const inline override virtual
Generic print-print function for this Activity.
Subclasses should override this function.
Reimplemented from SST::Action.
References SST::Activity::getDeliveryTime(), and SST::Output::output().
The documentation for this class was generated from the following file:
src/sst/core/stopAction.h