SST: SST::BaseComponent Class Reference
SST::BaseComponent Class Reference abstract
Main component object for the simulation.
#include <baseComponent.h>
Public Member Functions
ComponentId_t getId () const
Returns unique component ID.
virtual void emergencyShutdown (void)
Called when SIGINT or SIGTERM has been seen.
const std::string & getName () const
Returns component Name.
virtual void init (unsigned int UNUSED(phase))
Used during the init phase.
virtual void complete (unsigned int UNUSED(phase))
Used during the init phase.
virtual void setup ()
Called after all components have been constructed and initialization has completed, but before simulation time has begun.
virtual void finish ()
Called after simulation completes, but before objects are destroyed.
virtual bool Status ()
Currently unused function.
virtual void printStatus (Output &UNUSED(out))
Called by the Simulation to request that the component print it's current status.
bool isPortConnected (const std::string &name) const
Determine if a port name is connected to any links.
Link * configureLink (std::string name, TimeConverter *time_base, Event::HandlerBase *handler=NULL)
Configure a Link.
Link * configureLink (std::string name, std::string time_base, Event::HandlerBase *handler=NULL)
Configure a Link.
Link * configureLink (std::string name, Event::HandlerBase *handler=NULL)
Configure a Link.
Link * configureSelfLink (std::string name, TimeConverter *time_base, Event::HandlerBase *handler=NULL)
Configure a SelfLink (Loopback link)
Link * configureSelfLink (std::string name, std::string time_base, Event::HandlerBase *handler=NULL)
Configure a SelfLink (Loopback link)
Link * configureSelfLink (std::string name, Event::HandlerBase *handler=NULL)
Configure a SelfLink (Loopback link)
TimeConverter * registerClock (std::string freq, Clock::HandlerBase *handler, bool regAll=true)
Registers a clock for this component.
TimeConverter * registerClock (const UnitAlgebra &freq, Clock::HandlerBase *handler, bool regAll=true)
void unregisterClock (TimeConverter *tc, Clock::HandlerBase *handler)
Removes a clock handler from the component.
Cycle_t reregisterClock (TimeConverter *freq, Clock::HandlerBase *handler)
Reactivates an existing Clock and Handler.
Cycle_t getNextClockCycle (TimeConverter *freq)
Returns the next Cycle that the TimeConverter would fire.
TimeConverter * registerOneShot (std::string timeDelay, OneShot::HandlerBase *handler)
Registers a OneShot event for this component.
TimeConverter * registerOneShot (const UnitAlgebra &timeDelay, OneShot::HandlerBase *handler)
TimeConverter * registerTimeBase (std::string base, bool regAll=true)
Registers a default time base for the component and optionally sets the the component's links to that timebase.
TimeConverter * getTimeConverter (const std::string &base)
TimeConverter * getTimeConverter (const UnitAlgebra &base)
SimTime_t getCurrentSimTime (TimeConverter *tc) const
return the time since the simulation began in units specified by the parameter.
SimTime_t getCurrentSimTime () const
return the time since the simulation began in the default timebase
SimTime_t getCurrentSimTime (std::string base)
return the time since the simulation began in timebase specified
SimTime_t getCurrentSimTimeNano () const
Utility function to return the time since the simulation began in nanoseconds.
SimTime_t getCurrentSimTimeMicro () const
Utility function to return the time since the simulation began in microseconds.
SimTime_t getCurrentSimTimeMilli () const
Utility function to return the time since the simulation began in milliseconds.
template<typename T >
Statistic< T > * registerStatistic (std::string statName, std::string statSubId="")
Registers a statistic.
template<typename T >
Statistic< T > * registerStatistic (const char *statName, const char *statSubId="")
Module * loadModule (std::string type, Params &params)
Loads a module from an element Library.
Module * loadModuleWithComponent (std::string type, Component *comp, Params &params)
Loads a module from an element Library.
SubComponent * loadSubComponent (std::string type, Component *comp, Params &params)
Loads a SubComponent from an element Library.
SubComponent * loadNamedSubComponent (std::string name)
SubComponent * loadNamedSubComponent (std::string name, Params &params)
SubComponentSlotInfo * getSubComponentSlotInfo (std::string name, bool fatalOnEmptyIndex=false)
const std::vector< double > & getCoordinates () const
Retrieve the X,Y,Z coordinates of this component.
Protected Member Functions
void setDefaultTimeBase (TimeConverter *tc)
Manually set the default detaulTimeBase.
Link * selfLink (std::string name, Event::HandlerBase *handler=NULL)
Creates a new selfLink.
SharedRegion * getLocalSharedRegion (const std::string &key, size_t size)
Find a lookup table.
SharedRegion * getGlobalSharedRegion (const std::string &key, size_t size, SharedRegionMerger *merger=NULL)
Simulation * getSimulation () const
virtual bool doesComponentInfoStatisticExist (const std::string &statisticName) const =0
uint8_t getComponentInfoStatisticEnableLevel (const std::string &statisticName) const
std::string getComponentInfoStatisticUnits (const std::string &statisticName) const
virtual Component * getTrueComponent () const =0
virtual BaseComponent * getStatisticOwner () const =0
Returns self if Component If sub-component, returns self if a "modern" subcomponent otherwise, return base component.
Protected Attributes
TimeConverter * defaultTimeBase
Timebase used if no other timebase is specified for calls like BaseComponent::getCurrentSimTime().
ComponentInfo * my_info
Simulation * sim
ComponentInfo * currentlyLoadingSubComponent
Friends
class SubComponentSlotInfo_impl
class SST::Statistics::StatisticProcessingEngine
Detailed Description
Main component object for the simulation.
Member Function Documentation
virtual void SST::BaseComponent::complete (unsigned int UNUSEDphase) inline virtual
Used during the init phase.
The method will be called each phase of initialization. Initialization ends when no components have sent any data.
Reimplemented in SST::Interfaces::SimpleNetwork.
Link * SST::BaseComponent::configureLink (std::string name, TimeConverter * time_base, Event::HandlerBase * handler = NULL)
Configure a Link.
Parameters
name - Port Name on which the link to configure is attached.
time_base - Time Base of the link
handler - Optional Handler to be called when an Event is received
Returns
A pointer to the configured link, or NULL if an error occured.
References SST::LinkMap::getLink(), SST::Link::setDefaultTimeBase(), SST::Link::setFunctor(), and SST::Link::setPolling().
Referenced by configureLink(), and configureSelfLink().
Link * SST::BaseComponent::configureLink (std::string name, std::string time_base, Event::HandlerBase * handler = NULL)
Configure a Link.
Parameters
name - Port Name on which the link to configure is attached.
time_base - Time Base of the link
handler - Optional Handler to be called when an Event is received
Returns
A pointer to the configured link, or NULL if an error occured.
References configureLink().
Link * SST::BaseComponent::configureLink (std::string name, Event::HandlerBase * handler = NULL)
Configure a Link.
Parameters
name - Port Name on which the link to configure is attached.
handler - Optional Handler to be called when an Event is received
Returns
A pointer to the configured link, or NULL if an error occured.
References SST::LinkMap::getLink(), SST::Link::setFunctor(), and SST::Link::setPolling().
Link * SST::BaseComponent::configureSelfLink (std::string name, TimeConverter * time_base, Event::HandlerBase * handler = NULL)
Configure a SelfLink (Loopback link)
Parameters
name - Name of the self-link port
time_base - Time Base of the link
handler - Optional Handler to be called when an Event is received
Returns
A pointer to the configured link, or NULL if an error occured.
References configureLink().
Link * SST::BaseComponent::configureSelfLink (std::string name, std::string time_base, Event::HandlerBase * handler = NULL)
Configure a SelfLink (Loopback link)
Parameters
name - Name of the self-link port
time_base - Time Base of the link
handler - Optional Handler to be called when an Event is received
Returns
A pointer to the configured link, or NULL if an error occured.
References configureLink().
Link * SST::BaseComponent::configureSelfLink (std::string name, Event::HandlerBase * handler = NULL)
Configure a SelfLink (Loopback link)
Parameters
name - Name of the self-link port
handler - Optional Handler to be called when an Event is received
Returns
A pointer to the configured link, or NULL if an error occured.
References configureLink().
virtual void SST::BaseComponent::emergencyShutdown (void) inline virtual
Called when SIGINT or SIGTERM has been seen.
Allows components opportunity to clean up external state.
virtual void SST::BaseComponent::finish () inline virtual
Called after simulation completes, but before objects are destroyed.
A good place to print out statistics.
Reimplemented in SST::Interfaces::SimpleNetwork, and SST::SubComponent.
SimTime_t SST::BaseComponent::getCurrentSimTime (TimeConverter * tc) const
return the time since the simulation began in units specified by the parameter.
Parameters
tc TimeConverter specifying the units
References SST::TimeConverter::convertFromCoreTime().
SimTime_t SST::BaseComponent::getCurrentSimTime (std::string base)
return the time since the simulation began in timebase specified
Parameters
base Timebase frequency in SI Units
References getCurrentSimTime().
virtual void SST::BaseComponent::init (unsigned int UNUSEDphase) inline virtual
Used during the init phase.
The method will be called each phase of initialization. Initialization ends when no components have sent any data.
Reimplemented in SST::Interfaces::SimpleNetwork, and SST::SubComponent.
Module * SST::BaseComponent::loadModule (std::string type, Params & params)
Loads a module from an element Library.
Parameters
type Fully Qualified library.moduleName
params Parameters the module should use for configuration
Returns
handle to new instance of module, or NULL on failure.
Module * SST::BaseComponent::loadModuleWithComponent (std::string type, Component * comp, Params & params)
Loads a module from an element Library.
Parameters
type Fully Qualified library.moduleName
comp Pointer to component to pass to Module's constructor
params Parameters the module should use for configuration
Returns
handle to new instance of module, or NULL on failure.
SubComponent * SST::BaseComponent::loadSubComponent (std::string type, Component * comp, Params & params)
Loads a SubComponent from an element Library.
Parameters
type Fully Qualified library.moduleName
comp Pointer to component to pass to SuBaseComponent's constructor
params Parameters the module should use for configuration
Returns
handle to new instance of SubComponent, or NULL on failure.
virtual void SST::BaseComponent::printStatus (Output & UNUSEDout) inline virtual
Called by the Simulation to request that the component print it's current status.
Useful for debugging.
Parameters
out The Output class which should be used to print component status.
TimeConverter * SST::BaseComponent::registerClock (std::string freq, Clock::HandlerBase * handler, bool regAll = true)
Registers a clock for this component.
Parameters
freq Frequency for the clock in SI units
handler Pointer to Clock::HandlerBase which is to be invoked at the specified interval
regAll Should this clock period be used as the default time base for all of the links connected to this component
References defaultTimeBase, SST::LinkMap::getLinkMap(), and SST::Simulation::registerClock().
TimeConverter * SST::BaseComponent::registerOneShot (std::string timeDelay, OneShot::HandlerBase * handler)
Registers a OneShot event for this component.
Note: OneShot cannot be canceled, and will always callback after the timedelay.
Parameters
timeDelay Time delay for the OneShot in SI units
handler Pointer to OneShot::HandlerBase which is to be invoked at the specified interval
References SST::Simulation::registerOneShot().
template<typename T > Statistic<T>* SST::BaseComponent::registerStatistic (std::string statName, std::string statSubId = "") inline
Registers a statistic.
If Statistic is allowed to run (controlled by Python runtime parameters), then a statistic will be created and returned. If not allowed to run, then a NullStatistic will be returned. In either case, the returned value should be used for all future Statistic calls. The type of Statistic and the Collection Rate is set by Python runtime parameters. If no type is defined, then an Accumulator Statistic will be provided by default. If rate set to 0 or not provided, then the statistic will output results only at end of sim (if output is enabled).
Parameters
statName Primary name of the statistic. This name must match the defined ElementInfoStatistic in the component, and must also be enabled in the Python input file.
statSubId An additional sub name for the statistic
Returns
Either a created statistic of desired type or a NullStatistic depending upon runtime settings.
TimeConverter * SST::BaseComponent::registerTimeBase (std::string base, bool regAll = true)
Registers a default time base for the component and optionally sets the the component's links to that timebase.
Useful for components which do not have a clock, but would like a default timebase.
Parameters
base Frequency for the clock in SI units
regAll Should this clock period be used as the default time base for all of the links connected to this component
References defaultTimeBase, SST::LinkMap::getLinkMap(), SST::TimeLord::getTimeConverter(), and SST::Simulation::getTimeLord().
Cycle_t SST::BaseComponent::reregisterClock (TimeConverter * freq, Clock::HandlerBase * handler)
Reactivates an existing Clock and Handler.
Returns
time of next time clock handler will fire
References SST::Simulation::reregisterClock().
virtual void SST::BaseComponent::setup () inline virtual
Called after all components have been constructed and initialization has completed, but before simulation time has begun.
Reimplemented in SST::Interfaces::SimpleNetwork, and SST::SubComponent.
Field Documentation
TimeConverter* SST::BaseComponent::defaultTimeBase protected
Timebase used if no other timebase is specified for calls like BaseComponent::getCurrentSimTime().
Often set by BaseComponent::registerClock() function
Referenced by registerClock(), and registerTimeBase().
The documentation for this class was generated from the following files:
src/sst/core/baseComponent.h
src/sst/core/baseComponent.cc