SST: SST::Interfaces::SimpleMem Class Reference
SST::Interfaces::SimpleMem Class Reference abstract
Simplified, generic interface to Memory models.
#include <simpleMem.h>
Data Structures
class Handler
Event Handler class with user-data argument.
class Handler< classT, void >
Event Handler class without user-data.
class HandlerBase
Functor classes for Clock handling.
class Request
Represents both memory requests and responses.
Public Types
typedef uint64_t Addr
All Addresses can be 64-bit.
Public Member Functions
SimpleMem (SST::Component *comp, Params &UNUSED(params))
Constructor, designed to be used via 'loadSubComponent'.
virtual bool initialize (const std::string &linkName, HandlerBase *handler=NULL)=0
Second half of building the interface.
virtual void sendInitData (Request *req)=0
Sends a memory-based request during the init() phase.
virtual void sendInitData (SST::Event *ev)
Sends a generic Event during the init() phase (Mostly acts as a passthrough)
virtual SST::Event * recvInitData ()
Receive any data during the init() phase.
virtual SST::Link * getLink (void) const =0
Returns a handle to the underlying SST::Link.
virtual void sendRequest (Request *req)=0
Send a Request to the other side of the link.
virtual Request * recvResponse (void)=0
Receive a Request response from the side of the link.
Public Member Functions inherited from SST::SubComponent
SubComponent (Component *parent)
virtual void init (unsigned int UNUSED(phase)) override
Used during the init phase.
virtual void setup () override
Called after all components have been constructed and initialization has completed, but before simulation time has begun.
virtual void finish () override
Called after simulation completes, but before objects are destroyed.
Public Member Functions inherited from SST::BaseComponent
ComponentId_t getId () const
Returns unique component ID.
virtual void emergencyShutdown (void)
Called when SIGINT or SIGTERM has been seen.
const std::string & getName () const
Returns component Name.
virtual void complete (unsigned int UNUSED(phase))
Used during the init phase.
virtual bool Status ()
Currently unused function.
virtual void printStatus (Output &UNUSED(out))
Called by the Simulation to request that the component print it's current status.
bool isPortConnected (const std::string &name) const
Determine if a port name is connected to any links.
Link * configureLink (std::string name, TimeConverter *time_base, Event::HandlerBase *handler=NULL)
Configure a Link.
Link * configureLink (std::string name, std::string time_base, Event::HandlerBase *handler=NULL)
Configure a Link.
Link * configureLink (std::string name, Event::HandlerBase *handler=NULL)
Configure a Link.
Link * configureSelfLink (std::string name, TimeConverter *time_base, Event::HandlerBase *handler=NULL)
Configure a SelfLink (Loopback link)
Link * configureSelfLink (std::string name, std::string time_base, Event::HandlerBase *handler=NULL)
Configure a SelfLink (Loopback link)
Link * configureSelfLink (std::string name, Event::HandlerBase *handler=NULL)
Configure a SelfLink (Loopback link)
TimeConverter * registerClock (std::string freq, Clock::HandlerBase *handler, bool regAll=true)
Registers a clock for this component.
TimeConverter * registerClock (const UnitAlgebra &freq, Clock::HandlerBase *handler, bool regAll=true)
void unregisterClock (TimeConverter *tc, Clock::HandlerBase *handler)
Removes a clock handler from the component.
Cycle_t reregisterClock (TimeConverter *freq, Clock::HandlerBase *handler)
Reactivates an existing Clock and Handler.
Cycle_t getNextClockCycle (TimeConverter *freq)
Returns the next Cycle that the TimeConverter would fire.
TimeConverter * registerOneShot (std::string timeDelay, OneShot::HandlerBase *handler)
Registers a OneShot event for this component.
TimeConverter * registerOneShot (const UnitAlgebra &timeDelay, OneShot::HandlerBase *handler)
TimeConverter * registerTimeBase (std::string base, bool regAll=true)
Registers a default time base for the component and optionally sets the the component's links to that timebase.
TimeConverter * getTimeConverter (const std::string &base)
TimeConverter * getTimeConverter (const UnitAlgebra &base)
SimTime_t getCurrentSimTime (TimeConverter *tc) const
return the time since the simulation began in units specified by the parameter.
SimTime_t getCurrentSimTime () const
return the time since the simulation began in the default timebase
SimTime_t getCurrentSimTime (std::string base)
return the time since the simulation began in timebase specified
SimTime_t getCurrentSimTimeNano () const
Utility function to return the time since the simulation began in nanoseconds.
SimTime_t getCurrentSimTimeMicro () const
Utility function to return the time since the simulation began in microseconds.
SimTime_t getCurrentSimTimeMilli () const
Utility function to return the time since the simulation began in milliseconds.
template<typename T >
Statistic< T > * registerStatistic (std::string statName, std::string statSubId="")
Registers a statistic.
template<typename T >
Statistic< T > * registerStatistic (const char *statName, const char *statSubId="")
Module * loadModule (std::string type, Params &params)
Loads a module from an element Library.
Module * loadModuleWithComponent (std::string type, Component *comp, Params &params)
Loads a module from an element Library.
SubComponent * loadSubComponent (std::string type, Component *comp, Params &params)
Loads a SubComponent from an element Library.
SubComponent * loadNamedSubComponent (std::string name)
SubComponent * loadNamedSubComponent (std::string name, Params &params)
SubComponentSlotInfo * getSubComponentSlotInfo (std::string name, bool fatalOnEmptyIndex=false)
const std::vector< double > & getCoordinates () const
Retrieve the X,Y,Z coordinates of this component.
Additional Inherited Members
Protected Member Functions inherited from SST::SubComponent
Component * getTrueComponent () const finaloverride
BaseComponent * getStatisticOwner () const finaloverride
Returns self if Component If sub-component, returns self if a "modern" subcomponent otherwise, return base component.
SubComponent * loadSubComponent (std::string type, Params &params)
virtual bool doesComponentInfoStatisticExist (const std::string &statisticName) const finaloverride
Protected Member Functions inherited from SST::BaseComponent
void setDefaultTimeBase (TimeConverter *tc)
Manually set the default detaulTimeBase.
Link * selfLink (std::string name, Event::HandlerBase *handler=NULL)
Creates a new selfLink.
SharedRegion * getLocalSharedRegion (const std::string &key, size_t size)
Find a lookup table.
SharedRegion * getGlobalSharedRegion (const std::string &key, size_t size, SharedRegionMerger *merger=NULL)
Simulation * getSimulation () const
uint8_t getComponentInfoStatisticEnableLevel (const std::string &statisticName) const
std::string getComponentInfoStatisticUnits (const std::string &statisticName) const
Protected Attributes inherited from SST::SubComponent
Component *const parent
Protected Attributes inherited from SST::BaseComponent
TimeConverter * defaultTimeBase
Timebase used if no other timebase is specified for calls like BaseComponent::getCurrentSimTime().
ComponentInfo * my_info
Simulation * sim
ComponentInfo * currentlyLoadingSubComponent
Detailed Description
Simplified, generic interface to Memory models.
Constructor & Destructor Documentation
SST::Interfaces::SimpleMem::SimpleMem (SST::Component * comp, Params & UNUSEDparams) inline
Constructor, designed to be used via 'loadSubComponent'.
Member Function Documentation
virtual bool SST::Interfaces::SimpleMem::initialize (const std::string & linkName, HandlerBase * handler = NULL) pure virtual
Second half of building the interface.
Initialize with link name name, and handler, if any
Returns
true if the link was able to be configured.
virtual SST::Event* SST::Interfaces::SimpleMem::recvInitData () inline virtual
Receive any data during the init() phase.
See Also
SST::Link::recvInitData()
References getLink(), and SST::Link::recvInitData().
virtual Request* SST::Interfaces::SimpleMem::recvResponse (void) pure virtual
Receive a Request response from the side of the link.
Use this method for polling-based applications. Register a handler for push-based notification of responses.
Returns
NULL if nothing is available.
Pointer to a Request response (that should be deleted)
virtual void SST::Interfaces::SimpleMem::sendInitData (SST::Event * ev) inline virtual
Sends a generic Event during the init() phase (Mostly acts as a passthrough)
See Also
SST::Link::sendInitData()
References getLink(), and SST::Link::sendInitData().
The documentation for this class was generated from the following file:
src/sst/core/interfaces/simpleMem.h