class SITError(Exception):
    def __init__(self) -> None: ...

class APIException(SITError):
    def __init__(self, message: str) -> None: ...

class IPCException(SITError):
    def __init__(self, message: str) -> None: ...

class PortException(SITError):
    def __init__(self, message: str) -> None: ...

class SignalFormatException(SITError):
    def __init__(self, message: str) -> None: ...

class TemplateFileNotFound(SITError):
    def __init__(self, message: str) -> None: ...
