import pathlib

class Paths:
    def __init__(self, hdl_str: str, module_dir_path: str) -> None: ...
    def get_meta(self, key: str) -> pathlib.Path: ...
    def get_template(self, key: str) -> pathlib.Path: ...
    def get_gen(self, key: str) -> pathlib.Path: ...
    def get_paths(self) -> dict[str, pathlib.Path]: ...
    def set_template_paths(
        self, dir: str = ..., driver: str = ..., comp: str = ...
    ) -> None: ...
    def set_gen_paths(
        self, dir: str = ..., driver: str = ..., comp: str = ...
    ) -> None: ...
    def set_driver_path(self, driver_file: str) -> None: ...
    def set_comp_path(self, comp_file: str) -> None: ...
    def set_extra_file_paths(self, extra_files: dict[str, str]) -> None: ...
    def read_template_str(self, file: str) -> str: ...
