from typing import Literal

from ..sit import SIT

class SystemC(SIT):
    def __init__(
        self,
        module_name: str,
        lib: str,
        ipc: Literal["sock", "zmq"] = ...,
        module_dir: str = ...,
        lib_dir: str = ...,
        desc: str = ...,
        width_macros: dict[str, int] | None = ...,
    ) -> None: ...
    def _parse_signal_type(self, signal: str) -> int: ...
    def _get_driver_outputs(self) -> str: ...
    def _get_driver_inputs(self) -> str: ...
    def _get_driver_defs(self) -> dict[str, str]: ...
    def __get_driver_port_defs(self) -> str: ...
    def __get_driver_bindings(self) -> str: ...
    def _fixed_width_float_output(self) -> None: ...
    def _disable_runtime_warnings(self, warning: str) -> None: ...
