#!/usr/bin/env sh
set -o errexit

msgpack_url="https://github.com/msgpack/msgpack-c"
git clone --depth 1 -q ${msgpack_url} msgpack
mkdir -p src/msgpack
mv msgpack/include/* src/msgpack && rm -rf msgpack
