SST: SST::SyncManager Class Reference
SST::SyncManager Class Reference
Public Member Functions
SyncManager (const RankInfo &rank, const RankInfo &num_ranks, TimeConverter *minPartTC, SimTime_t min_part, const std::vector< SimTime_t > &interThreadLatencies)
ActivityQueue * registerLink (const RankInfo &to_rank, const RankInfo &from_rank, LinkId_t link_id, Link *link)
Register a Link which this Sync Object is responsible for.
void execute (void) override
Function which will be called when the time for this Activity comes to pass.
void exchangeLinkUntimedData (std::atomic< int > &msg_count)
Cause an exchange of Initialization Data to occur.
void finalizeLinkConfigurations ()
Finish link configuration.
void prepareForComplete ()
Prepare for complete() phase.
void print (const std::string &header, Output &out) const override
Generic print-print function for this Activity.
uint64_t getDataSize () const
Public Member Functions inherited from SST::Activity
void setDeliveryTime (SimTime_t time)
Set the time for which this Activity should be delivered.
SimTime_t getDeliveryTime () const
Return the time at which this Activity will be delivered.
int getPriority () const
Return the Priority of this Activity.
void setQueueOrder (uint64_t order)
Set a new Queue order.
Public Member Functions inherited from SST::Core::Serialization::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual std::string serialization_name () const =0
Additional Inherited Members
Protected Types inherited from SST::Core::Serialization::serializable
enum cxn_flag_t { ConstructorFlag }
Protected Member Functions inherited from SST::Action
void endSimulation ()
Called to signal to the Simulation object to end the simulation.
void endSimulation (SimTime_t end)
Protected Member Functions inherited from SST::Activity
void setPriority (int priority)
Set the priority of the Activity.
void serialize_order (SST::Core::Serialization::serializer &ser) override
Static Protected Member Functions inherited from SST::Core::Serialization::serializable
static void serializable_abort (uint32_t line, const char *file, const char *func, const char *obj)
Protected Attributes inherited from SST::Activity
int32_t enforce_link_order
Member Function Documentation
void SST::SyncManager::exchangeLinkUntimedData (std::atomic< int > & msg_count)
Cause an exchange of Initialization Data to occur.
Cause an exchange of Untimed Data to occur.
Referenced by SST::Simulation::complete(), and SST::Simulation::initialize().
void SST::SyncManager::execute (void) override virtual
Function which will be called when the time for this Activity comes to pass.
Implements SST::Activity.
References SST::Action::endSimulation().
void SST::SyncManager::print (const std::string & header, Output & out) const override virtual
Generic print-print function for this Activity.
Subclasses should override this function.
Reimplemented from SST::Action.
References SST::Activity::getDeliveryTime(), SST::Activity::getPriority(), and SST::Output::output().
The documentation for this class was generated from the following files:
src/sst/core/syncManager.h
src/sst/core/syncManager.cc