SST: SST::Statistics::StatisticOutput Class Reference
SST::Statistics::StatisticOutput Class Reference abstract
Forms the base class for statistics output generation within the SST core.
#include <statoutput.h>
Public Types
typedef
StatisticFieldInfo::fieldType_t fieldType_t
typedef
StatisticFieldInfo::fieldHandle_t fieldHandle_t
typedef std::vector
< StatisticFieldInfo * > FieldInfoArray_t
typedef std::unordered_map
< std::string, fieldHandle_t > FieldNameMap_t
Public Member Functions
StatisticOutput (Params &outputParameters)
Construct a base StatisticOutput.
std::string & getStatisticOutputName ()
Return the Statistic Output name.
Params & getOutputParameters ()
Return the parameters for the StatisticOutput.
virtual bool acceptsGroups () const
True if this StatOutput can handle StatisticGroups.
template<typename T >
fieldHandle_t registerField (const char *fieldName)
Register a field to be output (templated function)
StatisticFieldInfo * getRegisteredField (fieldHandle_t fieldHandle)
Adjust the hierarchy of the fields (FUTURE SUPPORT)
template<typename T >
StatisticFieldInfo * getRegisteredField (const char *statisticName, const char *fieldName)
Return the information on a registered field via known names.
FieldInfoArray_t & getFieldInfoArray ()
Return the array of registered field infos.
void outputField (fieldHandle_t fieldHandle, int32_t data)
Output field data.
void outputField (fieldHandle_t fieldHandle, uint32_t data)
void outputField (fieldHandle_t fieldHandle, int64_t data)
void outputField (fieldHandle_t fieldHandle, uint64_t data)
void outputField (fieldHandle_t fieldHandle, float data)
void outputField (fieldHandle_t fieldHandle, double data)
const char * getFieldTypeShortName (fieldType_t type)
Output field data.
Protected Member Functions
virtual bool checkOutputParameters ()=0
Have the Statistic Output check its parameters.
virtual void printUsage ()=0
Have Statistic Object print out its usage and parameter info.
virtual void implStartRegisterFields (StatisticBase *UNUSED(statistic))
virtual void implRegisteredField (fieldHandle_t UNUSED(fieldHandle))
virtual void implStopRegisterFields ()
virtual void startOfSimulation ()=0
Indicate to Statistic Output that simulation has started.
virtual void endOfSimulation ()=0
Indicate to Statistic Output that simulation has ended.
virtual void implStartOutputEntries (StatisticBase *statistic)=0
Indicate to Statistic Output that a statistic is about to send data to be output Allows object to perform any initialization before output.
virtual void implStopOutputEntries ()=0
Indicate to Statistic Output that a statistic is finished sending data to be output Allows object to perform any cleanup.
virtual void implStartRegisterGroup (StatisticGroup *UNUSED(group))
virtual void implStopRegisterGroup ()
virtual void implStartOutputGroup (StatisticGroup *UNUSED(group))
virtual void implStopOutputGroup ()
virtual void implOutputField (fieldHandle_t fieldHandle, int32_t data)=0
Implementation of outputField() for derived classes.
virtual void implOutputField (fieldHandle_t fieldHandle, uint32_t data)=0
virtual void implOutputField (fieldHandle_t fieldHandle, int64_t data)=0
virtual void implOutputField (fieldHandle_t fieldHandle, uint64_t data)=0
virtual void implOutputField (fieldHandle_t fieldHandle, float data)=0
virtual void implOutputField (fieldHandle_t fieldHandle, double data)=0
void setStatisticOutputName (std::string name)
void lock ()
void unlock ()
Friends
class SST::Simulation
class SST::Statistics::StatisticProcessingEngine
Detailed Description
Forms the base class for statistics output generation within the SST core.
Statistics are gathered by the statistic objects and then processed sent to the derived output object either periodically or by event and/or also at the end of the simulation. A single statistic output will be created by the simulation (per node) and will collect the data per its design.
Constructor & Destructor Documentation
SST::Statistics::StatisticOutput::StatisticOutput (Params & outputParameters)
Construct a base StatisticOutput.
Parameters
outputParameters - The parameters for the statistic Output.
Member Function Documentation
virtual bool SST::Statistics::StatisticOutput::checkOutputParameters () protected pure virtual
Have the Statistic Output check its parameters.
Returns
True if all parameters are ok; False if a parameter is missing or incorrect.
Implemented in SST::Statistics::StatisticOutputHDF5, SST::Statistics::StatisticOutputCSV, SST::Statistics::StatisticOutputTxt, SST::Statistics::StatisticOutputConsole, and SST::Statistics::StatisticOutputJSON.
virtual void SST::Statistics::StatisticOutput::endOfSimulation () protected pure virtual
Indicate to Statistic Output that simulation has ended.
Allows object to perform any shutdown required.
Implemented in SST::Statistics::StatisticOutputHDF5, SST::Statistics::StatisticOutputCSV, SST::Statistics::StatisticOutputTxt, SST::Statistics::StatisticOutputConsole, and SST::Statistics::StatisticOutputJSON.
FieldInfoArray_t& SST::Statistics::StatisticOutput::getFieldInfoArray () inline
Return the array of registered field infos.
Referenced by SST::Statistics::StatisticOutputCSV::implStartOutputEntries(), SST::Statistics::StatisticOutputTxt::startOfSimulation(), and SST::Statistics::StatisticOutputCSV::startOfSimulation().
const char * SST::Statistics::StatisticOutput::getFieldTypeShortName (fieldType_t type)
Output field data.
Parameters
type - The field type to get name of.
Returns
String name of the field type.
Referenced by SST::Statistics::StatisticOutputConsole::implOutputField(), SST::Statistics::StatisticOutputTxt::implOutputField(), and SST::Statistics::StatisticOutputCSV::startOfSimulation().
StatisticFieldInfo * SST::Statistics::StatisticOutput::getRegisteredField (fieldHandle_t fieldHandle)
Adjust the hierarchy of the fields (FUTURE SUPPORT)
Parameters
fieldHandle - The handle of the field to adjust.
Level - The level of the field.
parent - The parent field of the field. Return the information on a registered field via the field handle.
fieldHandle - The handle of the registered field.
Returns
Pointer to the registered field info.
Referenced by SST::Statistics::StatisticOutputConsole::implOutputField(), and SST::Statistics::StatisticOutputTxt::implOutputField().
template<typename T > StatisticFieldInfo* SST::Statistics::StatisticOutput::getRegisteredField (const char * statisticName, const char * fieldName) inline
Return the information on a registered field via known names.
Parameters
componentName - The name of the component.
statisticName - The name of the statistic.
fieldName - The name of the field .
Returns
Pointer to the registered field info.
virtual void SST::Statistics::StatisticOutput::implOutputField (fieldHandle_t fieldHandle, int32_t data) protected pure virtual
Implementation of outputField() for derived classes.
Perform the actual implementation of the output.
Implemented in SST::Statistics::StatisticOutputHDF5, SST::Statistics::StatisticOutputCSV, SST::Statistics::StatisticOutputTxt, SST::Statistics::StatisticOutputConsole, and SST::Statistics::StatisticOutputJSON.
Referenced by outputField().
virtual void SST::Statistics::StatisticOutput::implStartOutputEntries (StatisticBase * statistic) protected pure virtual
Indicate to Statistic Output that a statistic is about to send data to be output Allows object to perform any initialization before output.
Implemented in SST::Statistics::StatisticOutputHDF5, SST::Statistics::StatisticOutputCSV, SST::Statistics::StatisticOutputTxt, SST::Statistics::StatisticOutputConsole, and SST::Statistics::StatisticOutputJSON.
virtual void SST::Statistics::StatisticOutput::implStopOutputEntries () protected pure virtual
Indicate to Statistic Output that a statistic is finished sending data to be output Allows object to perform any cleanup.
Implemented in SST::Statistics::StatisticOutputHDF5, SST::Statistics::StatisticOutputCSV, SST::Statistics::StatisticOutputTxt, SST::Statistics::StatisticOutputConsole, and SST::Statistics::StatisticOutputJSON.
void SST::Statistics::StatisticOutput::outputField (fieldHandle_t fieldHandle, int32_t data)
Output field data.
Parameters
fieldHandle - The handle of the registered field.
data - The data to be output.
References implOutputField().
virtual void SST::Statistics::StatisticOutput::printUsage () protected pure virtual
Have Statistic Object print out its usage and parameter info.
Called when checkOutputParameters() returns false
Implemented in SST::Statistics::StatisticOutputHDF5, SST::Statistics::StatisticOutputCSV, SST::Statistics::StatisticOutputTxt, SST::Statistics::StatisticOutputConsole, and SST::Statistics::StatisticOutputJSON.
template<typename T > fieldHandle_t SST::Statistics::StatisticOutput::registerField (const char * fieldName) inline
Register a field to be output (templated function)
Parameters
fieldName - The name of the field.
Returns
The handle of the registered field or -1 if type is not supported. Note: Any field names (of the same data type) that are previously registered by a statistic will return the previously handle.
Referenced by SST::Statistics::AccumulatorStatistic< NumberBase >::registerOutputFields().
virtual void SST::Statistics::StatisticOutput::startOfSimulation () protected pure virtual
Indicate to Statistic Output that simulation has started.
Allows object to perform any setup required.
Implemented in SST::Statistics::StatisticOutputHDF5, SST::Statistics::StatisticOutputCSV, SST::Statistics::StatisticOutputTxt, SST::Statistics::StatisticOutputConsole, and SST::Statistics::StatisticOutputJSON.
The documentation for this class was generated from the following files:
src/sst/core/statapi/statoutput.h
src/sst/core/statapi/statoutput.cc