SST: SST::Statistics::StatisticOutputConsole Class Reference
SST::Statistics::StatisticOutputConsole Class Reference
The class for statistics output to the console.
#include <statoutputconsole.h>
Public Member Functions
StatisticOutputConsole (Params &outputParameters)
Construct a StatOutputConsole.
Public Member Functions inherited from SST::Statistics::StatisticOutput
StatisticOutput (Params &outputParameters)
Construct a base StatisticOutput.
std::string & getStatisticOutputName ()
Return the Statistic Output name.
Params & getOutputParameters ()
Return the parameters for the StatisticOutput.
virtual bool acceptsGroups () const
True if this StatOutput can handle StatisticGroups.
template<typename T >
fieldHandle_t registerField (const char *fieldName)
Register a field to be output (templated function)
StatisticFieldInfo * getRegisteredField (fieldHandle_t fieldHandle)
Adjust the hierarchy of the fields (FUTURE SUPPORT)
template<typename T >
StatisticFieldInfo * getRegisteredField (const char *statisticName, const char *fieldName)
Return the information on a registered field via known names.
FieldInfoArray_t & getFieldInfoArray ()
Return the array of registered field infos.
void outputField (fieldHandle_t fieldHandle, int32_t data)
Output field data.
void outputField (fieldHandle_t fieldHandle, uint32_t data)
void outputField (fieldHandle_t fieldHandle, int64_t data)
void outputField (fieldHandle_t fieldHandle, uint64_t data)
void outputField (fieldHandle_t fieldHandle, float data)
void outputField (fieldHandle_t fieldHandle, double data)
const char * getFieldTypeShortName (fieldType_t type)
Output field data.
Protected Member Functions
bool checkOutputParameters () override
Perform a check of provided parameters.
void printUsage () override
Print out usage for this Statistic Output.
void startOfSimulation () override
Indicate to Statistic Output that simulation started.
void endOfSimulation () override
Indicate to Statistic Output that simulation ended.
void implStartOutputEntries (StatisticBase *statistic) override
Implementation function for the start of output.
void implStopOutputEntries () override
Implementation function for the end of output.
void implOutputField (fieldHandle_t fieldHandle, int32_t data) override
Implementation functions for output.
void implOutputField (fieldHandle_t fieldHandle, uint32_t data) override
void implOutputField (fieldHandle_t fieldHandle, int64_t data) override
void implOutputField (fieldHandle_t fieldHandle, uint64_t data) override
void implOutputField (fieldHandle_t fieldHandle, float data) override
void implOutputField (fieldHandle_t fieldHandle, double data) override
Protected Member Functions inherited from SST::Statistics::StatisticOutput
virtual void implStartRegisterFields (StatisticBase *UNUSED(statistic))
virtual void implRegisteredField (fieldHandle_t UNUSED(fieldHandle))
virtual void implStopRegisterFields ()
virtual void implStartRegisterGroup (StatisticGroup *UNUSED(group))
virtual void implStopRegisterGroup ()
virtual void implStartOutputGroup (StatisticGroup *UNUSED(group))
virtual void implStopOutputGroup ()
void setStatisticOutputName (std::string name)
void lock ()
void unlock ()
Additional Inherited Members
Public Types inherited from SST::Statistics::StatisticOutput
typedef
StatisticFieldInfo::fieldType_t fieldType_t
typedef
StatisticFieldInfo::fieldHandle_t fieldHandle_t
typedef std::vector
< StatisticFieldInfo * > FieldInfoArray_t
typedef std::unordered_map
< std::string, fieldHandle_t > FieldNameMap_t
Detailed Description
The class for statistics output to the console.
This will be the default statistic output in SST.
Constructor & Destructor Documentation
SST::Statistics::StatisticOutputConsole::StatisticOutputConsole (Params & outputParameters)
Construct a StatOutputConsole.
Parameters
outputParameters - Parameters used for this Statistic Output
References SST::Simulation::getSimulationOutput(), and SST::Output::verbose().
Member Function Documentation
bool SST::Statistics::StatisticOutputConsole::checkOutputParameters () override protected virtual
Perform a check of provided parameters.
Returns
True if all required parameters and options are acceptable
Implements SST::Statistics::StatisticOutput.
References SST::Params::find(), and SST::Statistics::StatisticOutput::getOutputParameters().
void SST::Statistics::StatisticOutputConsole::endOfSimulation () override protected virtual
Indicate to Statistic Output that simulation ended.
Statistic output may perform any shutdown code here as necessary.
Implements SST::Statistics::StatisticOutput.
void SST::Statistics::StatisticOutputConsole::implOutputField (fieldHandle_t fieldHandle, int32_t data) override protected virtual
Implementation functions for output.
These will be called by the statistic to provide Statistic defined data to be output.
Parameters
fieldHandle - The handle to the registered statistic field.
data - The data related to the registered field to be output.
Implements SST::Statistics::StatisticOutput.
References SST::Statistics::StatisticFieldInfo::getFieldName(), SST::Statistics::StatisticFieldInfo::getFieldType(), SST::Statistics::StatisticOutput::getFieldTypeShortName(), and SST::Statistics::StatisticOutput::getRegisteredField().
void SST::Statistics::StatisticOutputConsole::implStartOutputEntries (StatisticBase * statistic) override protected virtual
Implementation function for the start of output.
This will be called by the Statistic Processing Engine to indicate that a Statistic is about to send data to the Statistic Output for processing.
Parameters
statistic - Pointer to the statistic object than the output can retrieve data from.
Implements SST::Statistics::StatisticOutput.
References SST::Statistics::StatisticBase::getFullStatName(), and SST::Statistics::StatisticBase::getStatTypeName().
void SST::Statistics::StatisticOutputConsole::implStopOutputEntries () override protected virtual
Implementation function for the end of output.
This will be called by the Statistic Processing Engine to indicate that a Statistic is finished sending data to the Statistic Output for processing. The Statistic Output can perform any output related functions here.
Implements SST::Statistics::StatisticOutput.
void SST::Statistics::StatisticOutputConsole::startOfSimulation () override protected virtual
Indicate to Statistic Output that simulation started.
Statistic output may perform any startup code here as necessary.
Implements SST::Statistics::StatisticOutput.
The documentation for this class was generated from the following files:
src/sst/core/statapi/statoutputconsole.h
src/sst/core/statapi/statoutputconsole.cc