SST: SST::NullEvent Class Reference
SST::NullEvent Class Reference
Null Event.
#include <event.h>
Public Member Functions
void execute (void) override
Cause this event to fire.
virtual void print (const std::string &header, Output &out) const override
Virtual function to "pretty-print" this event.
Public Member Functions inherited from SST::Event
virtual Event * clone ()
Clones the event in for the case of a broadcast.
void setDeliveryLink (LinkId_t id, Link *link)
Sets the link id used for delivery.
Link * getDeliveryLink ()
Gets the link id used for delivery.
void setRemoteEvent ()
For use by SST Core only.
LinkId_t getLinkId (void) const
Gets the link id associated with this event.
void serialize_order (SST::Core::Serialization::serializer &ser) override
Public Member Functions inherited from SST::Activity
void setDeliveryTime (SimTime_t time)
Set the time for which this Activity should be delivered.
SimTime_t getDeliveryTime () const
Return the time at which this Activity will be delivered.
int getPriority () const
Return the Priority of this Activity.
void setQueueOrder (uint64_t order)
Set a new Queue order.
Public Member Functions inherited from SST::Core::Serialization::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual std::string serialization_name () const =0
Additional Inherited Members
Public Types inherited from SST::Event
typedef std::pair< uint64_t, int > id_type
Type definition of unique identifiers.
Static Public Attributes inherited from SST::Event
static const id_type NO_ID = std::make_pair(0, -1)
Constant, default value for id_types.
Protected Types inherited from SST::Core::Serialization::serializable
enum cxn_flag_t { ConstructorFlag }
Protected Member Functions inherited from SST::Event
id_type generateUniqueId ()
Generates an ID that is unique across ranks, components and events.
Protected Member Functions inherited from SST::Activity
void setPriority (int priority)
Set the priority of the Activity.
Static Protected Member Functions inherited from SST::Core::Serialization::serializable
static void serializable_abort (uint32_t line, const char *file, const char *func, const char *obj)
Protected Attributes inherited from SST::Event
Link * delivery_link
Link used for delivery.
Protected Attributes inherited from SST::Activity
int32_t enforce_link_order
Detailed Description
Null Event.
Does nothing.
Member Function Documentation
virtual void SST::NullEvent::print (const std::string & header, Output & out) const inline override virtual
Virtual function to "pretty-print" this event.
Should be implemented by subclasses.
Reimplemented from SST::Event.
References SST::Activity::getDeliveryTime(), SST::Activity::getPriority(), and SST::Output::output().
The documentation for this class was generated from the following files:
src/sst/core/event.h
src/sst/core/event.cc