class BoilerPlateError(Exception):
    def __init__(self) -> None: ...

class APIException(BoilerPlateError):
    def __init__(self, message: str) -> None: ...

class IPCException(BoilerPlateError):
    def __init__(self, message: str) -> None: ...

class PortException(BoilerPlateError):
    def __init__(self, message: str) -> None: ...

class SignalFormatException(BoilerPlateError):
    def __init__(self, message: str) -> None: ...

class TemplateFileNotFound(BoilerPlateError):
    def __init__(self, message: str) -> None: ...
