include $(shell cocotb-config --makefiles)/Makefile.sim

VERILOG_SOURCES = {{module_dir}}/{{module_name}}.v
TOPLEVEL := {{module_name}}
MODULE   := {{module_name}}_driver
sim := iverilog

dumpconfig: $(SIM_BUILD)/sim.vvp $(CUSTOM_SIM_DEPS) $(COCOTB_LIBS) $(COCOTB_VPI_LIB)
	@echo "{\"PYTHONPATH\":\"$(LIB_DIR):$(PWD):$(NEW_PYTHONPATH)\",\
	\"LD_LIBRARY_PATH\":\"$(LIB_DIR):$(LD_LIBRARY_PATH)\",\
	\"COCOTB_REDUCED_LOG_FMT\":\"1\",\
	\"COCOTB_LOG_LEVEL\":\"CRITICAL\",\
	\"COCOTB_SIM\":\"1\",\
	\"MODULE\":\"$(MODULE)\",\
	\"TOPLEVEL\":\"$(TOPLEVEL)\",\
	\"TOPLEVEL_LANG\":\"verilog\",\
	\"FILE\":\"$(ICARUS_BIN_DIR)/vvp -M $(LIB_DIR) -m libcocotbvpi_icarus $(SIM_BUILD)/sim.vvp +ipc_proc=\"}" > config-cmd.json
